### ISSUE TITLE
Corrupt ReplayLog Resilience

### ISSUE THREAD

**Issue by louisburton** [emqx/replayq#2]
Powering off a system seems to easily produce scenarios where the replaylog becomes corrupt.
Upon subsequent start up, the system does not cope with the corrupt replaylog, and in my particular case leads to the emqx bridge not starting at all after failing to marshal the binary content of the replayq.
I'm not familiar with Erlang, but it looks to me like CRC checks are done to separate the Items from the Corrupted parts, but yet we still end up trying to marshal the Bin and this leads to exception.
https://github.com/emqx/replayq/blob/master/src/replayq.erl#L420-L461

Can the file be written to in a more cautious fashion, and in the case where corruption occurs, it be handled in a resilient fashion (i.e. just skipping the corrupted parts as looks like was intended?). I would not like any form of problems in reading back existing messages to stop the system coming up.

Version 4.1.0 of EMQ X.

```
bridge.mqtt.cloud.queue.replayq_dir=data/emqx_mqtt_bridge/
bridge.mqtt.cloud.queue.replayq_seg_bytes=10MB
```

```2020-06-23 08:27:35.786 [error] corrupted replayq log: data/emqx_mqtt_bridge/0000000001.replaylog, skipped 5 bytes
2020-06-23 08:27:35.792 [error] corrupted replayq log: data/emqx_mqtt_bridge/0000000001.replaylog, skipped 5 bytes
2020-06-23 08:27:35.792 [error] ** State machine emqx_bridge_worker_cloud terminating
** When server state  = {undefined,undefined}
** Reason for termination = error:badarg
** Callback modules = [emqx_bridge_worker]
** Callback mode = undefined
** Stacktrace =
**  [{erlang,binary_to_term,[<<>>],[]},
     {emqx_bridge_msg,from_binary,1,[]},
     {replayq,'-read_items/5-fun-1-',3,[]},
     {lists,map,2,[]},
     {replayq,open,1,[]},
     {emqx_bridge_worker,init,1,[]},
     {gen_statem,init_it,6,[]},
     {proc_lib,init_p_do_apply,3,[]}]

2020-06-23 08:27:35.792 [error]     supervisor: {local,emqx_bridge_mqtt_sup}
    errorContext: start_error
    reason: badarg
    offender: [{pid,undefined},
               {id,cloud},
               {mfargs,
                   {emqx_bridge_worker,start_link,
                       [cloud,
                        [{address,"x.x.x:443"},
                         {batch_size,32},
                         {bridge_mode,true},
                         {clean_start,false},
                         {clientid,"00:04:4b:c6:40:x"},
                         {connect_module,emqx_bridge_mqtt},
                         {forward_mountpoint,"etoc/00:04:4b:c6:40:x"},
                         {forwards,
                             ["reg/service/#","etoc/service/#","logs/#"]},
                         {keepalive,60},
                         {max_inflight_size,32},
                         {proto_ver,v4},
                         {queue,
                             #{max_total_size => 1048576000,
                               replayq_dir => "data/emqx_mqtt_bridge/",
                               replayq_seg_bytes => 10485760}},
                         {reconnect_delay_ms,30000},
                         {retry_interval,20000},
                         {ssl,true},
                         {ssl_opts,[{versions,['tlsv1.2','tlsv1.1',tlsv1]}]},
                         {start_type,auto},
                         {subscriptions,[{"ctoe/00:04:4b:c6:40:x/#",1}]},
                         {username,"00:04:4b:c6:40:x"}]]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
2020-06-23 08:27:35.800 [error]   crasher:
    initial call: application_master:init/4
    pid: <0.1314.0>
    registered_name: []
    exception exit: {{shutdown,{failed_to_start_child,cloud,badarg}},
                     {emqx_bridge_mqtt_app,start,[normal,[]]}}
      in function  application_master:init/4
    ancestors: [<0.1313.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.1315.0>,normal}]
    links: [<0.1313.0>,<0.973.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 187
  neighbours:

2020-06-23 08:27:35.793 [error]   crasher:
    initial call: emqx_bridge_worker:init/1
    pid: <0.1317.0>
    registered_name: []
    exception error: bad argument
      in function  binary_to_term/1
         called as binary_to_term(<<>>)
      in call from emqx_bridge_msg:from_binary/1
      in call from replayq:'-read_items/5-fun-1-'/3
      in call from lists:map/2
      in call from replayq:open/1
      in call from emqx_bridge_worker:init/1
      in call from gen_statem:init_it/6
    ancestors: [emqx_bridge_mqtt_sup,<0.1315.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.1316.0>,
                          {shutdown,{failed_to_start_child,cloud,badarg}}}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 41284
  neighbours:

2020-06-23 08:27:35.814 [error] [Plugins] Load plugin emqx_bridge_mqtt failed, cannot start plugin emqx_bridge_mqtt for {{shutdown,{failed_to_start_child,cloud,badarg}},{emqx_bridge_mqtt_app,start,[normal,[]]}}
```

[0000000001.replaylog.txt](https://github.com/emqx/replayq/files/4818658/0000000001.replaylog.txt)

**Comment by louisburton** [comment]
@zhanghongtong Hi Rory, I notice you have handled my other two tickets very promptly and I thank you for that. Just checking this one (the biggest issue for us) doesn't need similar queueing? Thanks!

**Comment by Rory-Z** [comment]
Hi, @louisburton 
Sorry I'm not familiar with the code here,  maybe @terry-xiaoyu  can help you

**Comment by terry-xiaoyu** [comment]
@louisburton Did you configure more than one nodes to use the same `bridge.mqtt.cloud.queue.replayq_dir`? This would cause the replay files corrupt.

**Comment by spring2maz** [comment]
Hi.
This looks like a corner case which is not covered in corrupted tail truncation.
I will have a look at it later today.

**Comment by louisburton** [comment]
@spring2maz thanks very much for taking a look so promptly.

@terry-xiaoyu We actually only have one container running on our edge device looking at the `bridge.mqtt.cloud.queue.replayq_dir`. It is configured to a sub folder within the `data` Volume specified [within the EMQ X Dockerfile ](https://github.com/emqx/emqx-rel/blob/v4.1.0/deploy/docker/Dockerfile#L57).
I've had to turn this off temporarily, as the impact of no MQTT communication was much worse than losing messages on restart, but I would much rather have persistence without the risk of ever stopping the bridge from starting.
Thanks guys!

**Comment by louisburton** [comment]
@zhanghongtong I notice the `v4.2-alpha.2` release tag was created a couple of days ago.
It looks like it might not include `replayq` `0.2.0` (https://github.com/emqx/emqx-bridge-mqtt/blob/v4.2-alpha.2/rebar.config#L2) which has this fix which I'd like to test. Is this missed perhaps?
Would love to get a release I can test with this in 😄  thx! 

Since seen this : https://github.com/emqx/emqx-bridge-mqtt/commit/f98ff3defd9829e72875893d5e8e4bbcf3e78daf#r40841085
So the change has been committed, just not merged to any release tags yet.
